import os
import sys

from g2p_en import G2p
g2p = G2p()


def en_g2p(word):
    phn_out = g2p(word)
    for i, phn in enumerate(phn_out):
        if phn in cmu_2_cls_map.keys():
            phn_out[i] = cmu_2_cls_map[phn]
            if phn_out[i] in cls_2_chr_map.keys():
                phn_out[i] = cls_2_chr_map[phn_out[i]]
            else:
                pass
        else:
            pass
    return ("".join(phn_out)).strip().replace(" ", "")

cmu_2_cls_map = {
            "AA": "aa",
            "AA0": "aa",
            "AA1": "aa",
            "AA2": "aa",
            "AE": "axx",
            "AE0": "axx",
            "AE1": "axx",
            "AE2": "axx",
            "AH": "a",
            "AH0": "a",
            "AH1": "a",
            "AH2": "a",
            "AO": "ax",
            "AO0": "ax",
            "AO1": "ax",
            "AO2": "ax",
            "AW": "ou",
            "AW0": "ou",
            "AW1": "ou",
            "AW2": "ou",
            "AX": "a",
            "AY": "ei",
            "AY0": "ei",
            "AY1": "ei",
            "AY2": "ei",
            "B": "b",
            "CH": "c",
            "D": "dx",
            "DH": "d",
            "EH": "ee",
            "EH0": "ee",
            "EH1": "ee",
            "EH2": "ee",
            "ER": "a r",
            "ER0": "a r",
            "ER1": "a r",
            "ER2": "a r",
            "EY": "ee",
            "EY0": "ee",
            "EY1": "ee",
            "EY2": "ee",
            "F": "f",
            "G": "g",
            "HH": "h",
            "IH": "i",
            "IH0": "i",
            "IH1": "i",
            "IH2": "i",
            "IY": "ii",
            "IY0": "ii",
            "IY1": "ii",
            "IY2": "ii",
            "JH": "j",
            "K": "k",
            "L": "l",
            "M": "m",
            "N": "n",
            "NG": "ng",
            "OW": "o",
            "OW0": "o",
            "OW1": "o",
            "OW2": "o",
            "OY": "ei",
            "OY0": "ei",
            "OY1": "ei",
            "OY2": "ei",
            "P": "p",
            "R": "r",
            "S": "s",
            "SH": "sh",
            "T": "tx",
            "TH": "t",
            "UH": "u",
            "UH0": "u",
            "UH1": "u",
            "UH2": "u",
            "UW": "uu",
            "UW0": "uu",
            "UW1": "uu",
            "UW2": "uu",
            "V": "w",
            "W": "w",
            "Y": "y",
            "Z": "z",
            "ZH": "sh",
        }
cls_2_chr_map = {
            "aa": "A",
            "ii": "I",
            "uu": "U",
            "ee": "E",
            "oo": "O",
            "nn": "N",
            "ae": "ऍ",
            "ag": "ऽ",
            "au": "औ",
            "axx": "अ",
            "ax": "ऑ",
            "bh": "B",
            "ch": "C",
            "dh": "ध",
            "dx": "ड",
            "dxh": "ढ",
            "dxhq": "T",
            "dxq": "D",
            "ei": "ऐ",
            "ai": "ऐ",
            "eu": "உ",
            "gh": "घ",
            "gq": "G",
            "hq": "H",
            "jh": "J",
            "kh": "ख",
            "khq": "K",
            "kq": "क",
            "ln": "ൾ",
            "lw": "ൽ",
            "lx": "ള",
            "mq": "M",
            "nd": "न",
            "ng": "ङ",
            "nj": "ञ",
            "nk": "Y",
            "nw": "ൺ",
            "nx": "ण",
            "ou": "औ",
            "ph": "P",
            "rq": "R",
            "rqw": "ॠ",
            "rw": "ർ",
            "rx": "र",
            "sh": "श",
            "sx": "ष",
            "th": "थ",
            "tx": "ट",
            "txh": "ठ",
            "wv": "W",
            "zh": "Z",
        }
input = sys.argv[1]

print(en_g2p(input))
